[package]
name = "specs-derive"
version = "0.2.1"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Custom derive macro for Specs components"
documentation = "https://docs.rs/specs-derive"
repository = "https://github.com/slide-rs/specs/tree/master/specs-derive"
keywords = ["gamedev", "parallel", "specs", "ecs", "derive"]
license = "MIT/Apache-2.0"

[dependencies]
syn = { version = "0.12", features = ["extra-traits"] }
quote = "0.4"

[dev-dependencies]
specs = { path = "..", features = ["serde"] }
serde = "1"

[lib]
proc-macro = true
