language: rust
rust:
- nightly
- stable

branches:
  only:
    - staging
    - trying
    - master

script:
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
- cargo build --verbose --features serialize
- cargo test --verbose --features serialize
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --verbose --no-run;
  fi

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  travis login --org --github-token ${GH_TOKEN} &&
  travis restart -r slide-rs/specs-website

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
