language: rust
rust:
- nightly
- stable

cache: cargo

branches:
  only:
    - staging
    - trying
    - master

before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt

script:
- cargo fmt -- --write-mode=diff
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
- cargo build --verbose --features serialize
- cargo test --verbose --features serialize
- cargo build --verbose --features rudy
- cargo test --verbose --features rudy
- cargo build --verbose --features common
- cargo test --verbose --features common
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --verbose --no-run;
  fi
- cargo build --manifest-path ./specs-derive/Cargo.toml --verbose
- cargo test --manifest-path ./specs-derive/Cargo.toml --verbose

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  gem install travis -v 1.8.8 --no-rdoc --no-ri &&
  travis login --org --no-interactive --github-token ${GH_TOKEN} &&
  travis restart --no-interactive -r slide-rs/specs-website

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
