[package]
name = "specs"
version = "0.10.0"
description = """
Specs is an Entity-Component System library written in Rust.
"""
documentation = "https://docs.rs/specs/"
repository = "https://github.com/slide-rs/specs"
homepage = "https://slide-rs.github.io/"
readme = "README.md"
keywords = ["gamedev"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
authors = ["slide-rs hackers"]
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "slide-rs/specs" }

[dependencies]
crossbeam = "0.3.0"
derivative = "1"
fnv = "1.0"
hibitset = { version = "0.4.1", features = ["parallel"] }
mopa = "0.2"
shred = "0.6.0"
shrev = "0.8.0"
shred-derive = "0.4"
tuple_utils = "0.2"
rayon = "0.8.2"

futures = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }

# enable rudy via --features rudy
rudy = { version = "0.1", optional = true }

[features]
common = ["futures"]
nightly = []

[package.metadata.docs.rs]
features = ["common", "serde"]

[dev-dependencies]
cgmath =  { version = "0.14", features = ["eders"] }
ron = "0.1.3"
rand = "0.3"
serde_json = "1.0"
specs-derive = { path = "specs-derive", version = "0.2.0" }

[[example]]
name = "async"

[[example]]
name = "basic"

[[example]]
name = "full"

[[example]]
name = "cluster_bomb"

[[example]]
name = "bitset"

[[example]]
name = "track"

[[example]]
name = "common"
required-features = ["common"]

[[example]]
name = "serialize"
required-features = ["serde"]

[[example]]
name = "saveload"
required-features = ["serde"]

[workspace]
members = ["specs-derive"]

