[package]
name = "specs"
version = "0.11.0-alpha6"
description = """
Specs is an Entity-Component System library written in Rust.
"""
documentation = "https://docs.rs/specs/"
repository = "https://github.com/slide-rs/specs"
homepage = "https://slide-rs.github.io/"
readme = "README.md"
keywords = ["gamedev", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
authors = ["slide-rs hackers"]
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "slide-rs/specs" }

[dependencies]
crossbeam = "0.3.0"
derivative = "1"
fnv = "1.0"
hibitset = { version = "0.5.0", features = ["parallel"] }
log = "0.4"
mopa = "0.2"
shred = "0.7.0-alpha5"
shrev = "1.0.0"
shred-derive = "0.5.0-alpha1"
tuple_utils = "0.2"
rayon = "1.0.0"

futures = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }

# enable rudy via --features rudy
rudy = { version = "0.1", optional = true }

[features]
common = ["futures"]
nightly = []

[package.metadata.docs.rs]
features = ["common", "serde"]

[dev-dependencies]
cgmath =  { version = "0.14", features = ["eders"] }
criterion = "0.2"
ron = "0.2"
rand = "0.3"
serde_json = "1.0"
specs-derive = { path = "specs-derive", version = "0.2.0" }

[[example]]
name = "async"

[[example]]
name = "basic"

[[example]]
name = "full"

[[example]]
name = "cluster_bomb"

[[example]]
name = "bitset"

[[example]]
name = "track"

[[example]]
name = "common"
required-features = ["common"]

[[example]]
name = "saveload"
required-features = ["serde"]

[[bench]]
name = "benches_main"
harness = false

[[bench]]
name = "parallel"

[[bench]]
name = "world"
harness = false

[workspace]
members = ["specs-derive"]
