[package]
name = "specs"
version = "0.8.0"
description = """
Parallel Entity-Component System.

Specs is a parallel ECS in Rust. It combines the performance of the beast with the flexibility of a cat.

Objectives:

- Automatically parallelize workload, while following Rust ownership rules applied to the components.
- Do not restrict the storage implementation for a particular component.
- Place no constraints onto the component types themselves, allow defining them in user modules.
- Have low overhead, high safety, and optimal ergonomics.
"""
documentation = "https://slide-rs.github.io/specs/"
repository = "https://github.com/slide-rs/specs"
keywords = ["gamedev"]
license = "Apache-2.0"
authors = ["slide-rs hackers"]
exclude = ["doc", ".travis.yml"]

[dependencies]
atom = "0.3"
fnv = "1.0"
mopa = "0.2"
ticketed_lock = "0.1"
tuple_utils = "0.2"

pulse = { version = "0.5", optional = true }

serde = { version = "0.9.11", optional = true }
serde_derive = { version = "0.9.11", optional = true }

[dependencies.rayon]
version = "0.7"
optional = true
features = ["unstable"]

[features]
default = ["parallel"]
parallel = ["pulse", "rayon"]
serialize = ["serde", "serde_derive"]

[dev-dependencies]
serde_json = "0.9.9"
