[package]
name = "specs"
version = "0.14.1"
description = """
Specs is an Entity-Component System library written in Rust.
"""
documentation = "https://docs.rs/specs/"
repository = "https://github.com/slide-rs/specs"
homepage = "https://slide-rs.github.io/"
readme = "README.md"
keywords = ["gamedev", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
authors = ["slide-rs hackers"]
exclude = ["bors.toml", ".travis.yml"]

# the `storage_cmp` and `storage_sparse` benches are called from `benches_main`
autobenches = false

[badges]
travis-ci = { repository = "slide-rs/specs" }

[dependencies]
crossbeam = "0.4.1"
derivative = "1"
fnv = "1.0"
hibitset = { version = "0.5.3", default-features = false }
log = "0.4"
mopa = "0.2"
shred = { version = "0.7.0", default-features = false }
shrev = "1.0.0"
shred-derive = "0.5.0"
tuple_utils = "0.2"
rayon = { version = "1.0.0", optional = true }
nonzero_signed = "1.0.1"

futures = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }

# enable rudy via --features rudy
rudy = { version = "0.1", optional = true }

[features]
default = ["parallel"]
parallel = ["rayon", "shred/parallel", "hibitset/parallel"]
common = ["futures"]
nightly = ["shred/nightly"]

[package.metadata.docs.rs]
features = ["common", "serde"]

[dev-dependencies]
cgmath =  { version = "0.16" }
criterion = "0.2"
ron = "0.4"
rand = "0.5.5"
serde_json = "1.0"
specs-derive = { path = "specs-derive", version = "0.3.0" }

[[example]]
name = "async"

[[example]]
name = "basic"

[[example]]
name = "full"

[[example]]
name = "cluster_bomb"

[[example]]
name = "bitset"

[[example]]
name = "track"

[[example]]
name = "ordered_track"

[[example]]
name = "common"
required-features = ["common"]

[[example]]
name = "saveload"
required-features = ["serde"]

[[bench]]
name = "benches_main"
harness = false

[[bench]]
name = "parallel"

[[bench]]
name = "world"
harness = false

[workspace]
members = ["specs-derive"]
