# See docs: https://embarkstudios.github.io/cargo-deny/checks/index.html

[advisories]
unmaintained = "warn"
vulnerability = "warn"
yanked = "deny"
notice = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"
skip = [
    { name = "itertools", version = "0.9.0" }, # criterion brings in two versions
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[licenses]
copyleft = "deny"

# Run `cargo deny list` to see which crates use which license
# and add them to this array if we accept them

allow = ["MIT", "Apache-2.0", "Unlicense", "BSD-3-Clause"]

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]
