# The URL the site will be built for
base_url = "https://zola-even.netlify.com"

compile_sass = true
title = "even theme"
description = ""
highlight_code = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Vincent"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Even"
