name: Website

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUSTFLAGS: -Cdebuginfo=0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  Ref-and-Tutorial:
    name: Doc Reference + Tutorials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs/reference
            docs/tutorials

      - name: Build Books
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.4.37

      - run: mdbook build docs/reference --dest-dir ${GITHUB_WORKSPACE}/public/docs/reference
      - run: mdbook build docs/tutorials --dest-dir ${GITHUB_WORKSPACE}/public/docs/tutorials

      - uses: actions/upload-artifact@v4
        with:
          name: Doc Reference
          path: |
            public/docs/reference
      - uses: actions/upload-artifact@v4
        with:
          name: Doc Tutorials
          path: |
            public/docs/tutorials

  Rust-API:
    name: Doc Rust API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rust-docs

      - name: Build API Doc
        env:
          FEATURES: parallel serde derive uuid_entity storage-event-control
        run: cargo doc --all --features "${FEATURES}" # --no-deps

      - uses: actions/upload-artifact@v4
        with:
          name: Doc Rust API
          path: |
            target/doc
